[package]
edition = "2024"
name = "absurd-sqlite-deno-runtime"
version = "0.1.0"

[dependencies]
deno_ast = { version = "0.52.0", features = ["transpiling"] }
deno_core = "0.376.0"
deno_error = "0.7.3"
tokio = { version = "1.48.0", features = ["full"] }
url = "2.5.7"
